name: Run Jest Tests & Deploy to Netlify
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn Modules
      run: yarn
    - name: Run Jest Tests
      run: yarn test "../__tests__"
  
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/608a80ec1fad5ef8bce687f6
