name: Run Jest Tests & Deploy to Netlify
env:
      YELP_API_KEY: ${{ secrets.YELP_API_KEY }}
on: 
  push:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Yarn Modules
      run: yarn
    - name: Run Jest Tests
      run: yarn test "../__tests__"
  
  build:
    name: Request Netlify Webhook
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/608f8e3560b9e5b39f75bdfa
